### ISSUE TITLE
avs install error

### ISSUE THREAD

**Issue by zuowanbushiwo** [respeaker/avs#1]
Hi :
root@ReSpeaker:/# pip install avs
Requirement already satisfied (use --upgrade to upgrade): avs in /usr/lib/python2.7/site-packages
Downloading/unpacking hyper (from avs)
  Downloading hyper-0.7.0-py2.py3-none-any.whl (269kB): 269kB downloaded
Requirement already satisfied (use --upgrade to upgrade): tornado in /usr/lib/python2.7/site-packages (from avs)
Requirement already satisfied (use --upgrade to upgrade): requests in /usr/lib/python2.7/site-packages (from avs)
Downloading/unpacking service-identity>=14.0.0 (from hyper->avs)
  Downloading service_identity-17.0.0-py2.py3-none-any.whl
Downloading/unpacking h2>=2.4,<3.0 (from hyper->avs)
  Downloading h2-2.6.2-py2.py3-none-any.whl (71kB): 71kB downloaded
Downloading/unpacking pyOpenSSL>=0.15 (from hyper->avs)
  Downloading pyOpenSSL-17.1.0-py2.py3-none-any.whl (53kB): 53kB downloaded
Downloading/unpacking hyperframe>=3.2,<4.0 (from hyper->avs)
  Downloading hyperframe-3.2.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): singledispatch in /usr/lib/python2.7/site-packages (from tornado->avs)
Requirement already satisfied (use --upgrade to upgrade): certifi in /usr/lib/python2.7/site-packages (from tornado->avs)
Requirement already satisfied (use --upgrade to upgrade): backports-abc>=0.4 in /usr/lib/python2.7/site-packages (from tornado->avs)
Downloading/unpacking pyasn1 (from service-identity>=14.0.0->hyper->avs)
  Downloading pyasn1-0.2.3-py2.py3-none-any.whl (53kB): 53kB downloaded
Downloading/unpacking pyasn1-modules (from service-identity>=14.0.0->hyper->avs)
  Downloading pyasn1_modules-0.0.9-py2.py3-none-any.whl (60kB): 60kB downloaded
Downloading/unpacking attrs (from service-identity>=14.0.0->hyper->avs)
  Downloading attrs-17.2.0-py2.py3-none-any.whl
Downloading/unpacking hpack>=2.2,<4 (from h2>=2.4,<3.0->hyper->avs)
  Downloading hpack-3.0.0-py2.py3-none-any.whl
Downloading/unpacking enum34>=1.0.4,<2 (from h2>=2.4,<3.0->hyper->avs)
  Downloading enum34-1.1.6-py2-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): six>=1.5.2 in /usr/lib/python2.7/site-packages (from pyOpenSSL>=0.15->hyper->avs)
Downloading/unpacking cryptography>=1.9 (from pyOpenSSL>=0.15->hyper->avs)
  Downloading cryptography-2.0.tar.gz (432kB): 432kB downloaded
  Running setup.py (path:/tmp/pip_build_root/cryptography/setup.py) egg_info for package cryptography
    
    no previously-included directories found matching 'docs/_build'
    warning: no previously-included files matching '*' found under directory 'vectors'
Downloading/unpacking idna>=2.1 (from cryptography>=1.9->pyOpenSSL>=0.15->hyper->avs)
  Downloading idna-2.5-py2.py3-none-any.whl (55kB): 55kB downloaded
Downloading/unpacking asn1crypto>=0.21.0 (from cryptography>=1.9->pyOpenSSL>=0.15->hyper->avs)
  Downloading asn1crypto-0.22.0-py2.py3-none-any.whl (97kB): 97kB downloaded
Downloading/unpacking ipaddress (from cryptography>=1.9->pyOpenSSL>=0.15->hyper->avs)
  Downloading ipaddress-1.0.18-py2-none-any.whl
Downloading/unpacking cffi>=1.7 (from cryptography>=1.9->pyOpenSSL>=0.15->hyper->avs)
  Downloading cffi-1.10.0.tar.gz (418kB): 418kB downloaded
  Running setup.py (path:/tmp/pip_build_root/cffi/setup.py) egg_info for package cffi
    unable to execute 'mipsel-openwrt-linux-uclibc-gcc': No such file or directory
    unable to execute 'mipsel-openwrt-linux-uclibc-gcc': No such file or directory
    
        No working compiler found, or bogus compiler options
        passed to the compiler from Python's distutils module.
        See the error messages above.
        (If they are about -mno-fused-madd and you are on OS/X 10.8,
        see http://stackoverflow.com/questions/22313407/ .)
    Complete output from command python setup.py egg_info:
    unable to execute 'mipsel-openwrt-linux-uclibc-gcc': No such file or directory

unable to execute 'mipsel-openwrt-linux-uclibc-gcc': No such file or directory

    No working compiler found, or bogus compiler options

    passed to the compiler from Python's distutils module.

    See the error messages above.

    (If they are about -mno-fused-madd and you are on OS/X 10.8,

    see http://stackoverflow.com/questions/22313407/ .)

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/cffi
Storing debug log for failure in /root/.pip/pip.log

why？

**Comment by xiongyihui** [comment]
I've installed avs with no error:
```
root@ReSpeaker:~# pip install avs
Dowloading/unpacking avs
  Downloading avs-0.0.4-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): requests in /usr/lib/python2.7/site-packages (from avs)
Requirement already satisfied (use --upgrade to upgrade): tornado in /usr/lib/python2.7/site-packages (from avs)
Downloading/unpacking hyper (from avs)
  Downloading hyper-0.7.0-py2.py3-none-any.whl (269kB): 269kB downloaded
Requirement already satisfied (use --upgrade to upgrade): singledispatch in /usr/lib/python2.7/site-packages (from tornado->avs)
Requirement already satisfied (use --upgrade to upgrade): certifi in /usr/lib/python2.7/site-packages (from tornado->avs)
Requirement already satisfied (use --upgrade to upgrade): backports-abc>=0.4 in /usr/lib/python2.7/site-pacages (from tornado->avs)
Downloading/unpacking h2>=2.4,<3.0 (from hyper->avs)
  Downloading h2-2.6.2-py.py3-none-any.whl (71kB): 71kB downloaded
Downloading/unpacking hyperframe>=3.2,<4.0 (from hyer->avs)
  Downloading hyperframe-3.2.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): six in /usr/lib/python2.7/site-packages (fom singledispatch->tornado->avs)
Downloading/unpacking hpack>=2.2,<4 (from h2>=2.4,<3.0->hyper->avs)
  Downloading hpack-3.0.0-py2.py3-none-anywhl
Downloading/unpacking enum34>=1.0.4,<2 (from h2>=2.4,<3.0->hyper->avs)
  Downloading enum34-1.1.6-py2-none-any.whl
Installing collected packages: avs, hyper, h2, hyperframe, hpack, enum34
Successfully installed avs hyper h2 hyperframe hpack enum34
Cleaning up...
```

Maybe run `firstboot` and reboot, then run `pip install avs`
