### ISSUE TITLE
如何融合为单通道

### ISSUE THREAD

**Issue by 1158114251** [respeaker/avs#12]
我使用树莓派4麦克风阵列那块板子，我一开始以为录制完语音就融合为一个通道，但是录制的时候看到wiki上面说是录制的是4通道，但是各大语音平台都是要求上传的语音都是单通道的，比如百度，讯飞都是单通道16000采样率，请教如何把4通道转出单通道，目前我直接使用4通道声音上传语音平台，报错，识别不出，我强制用arecord录制单通道依旧不行。

**Comment by xiongyihui** [comment]
可以用 https://github.com/voice-engine/voice-engine
