### ISSUE TITLE
On Openwrt Facing issues with gi and gst 

### ISSUE THREAD

**Issue by yerasiprathyusha** [respeaker/avs#18]
* Python Alexa Voice Service version: V2
* Python version: 2.7
* Operating System: Openwrt

### Description
Trying to use respeaker-avs on openwrt .. Unable to  install pygobject for openwrt, To use import gi..

**Comment by xiongyihui** [comment]
The pygobject is installed by default.
You just need to run `pip install avs` to install it.

**Comment by yerasiprathyusha** [comment]
In my case  pygobject is not installed by default.. And facing issues while cross compiling the pygobject package..

**Comment by xiongyihui** [comment]
1. are you trying to build an openwrt firmware from sources? The pygobject package is at https://github.com/respeaker/respeaker-feed/tree/master/pygobject

2. gstreamer has great capability of encoding and decoding, but as we just recording raw audio, gstreamer is not necessary. I never try to use gstreamer to record audio. If you have two applications to use the mic, ALSA dsnoop plugin is an option. https://alsa.opensrc.org/Dsnoop
