### ISSUE TITLE
Alexa cannot talk back!

### ISSUE THREAD

**Issue by wangzt12** [respeaker/avs#19]
* Python Alexa Voice Service version:
* Python version:
* Operating System:

### Description

Hi! I was trying to follow this instruction: https://github.com/SeeedDocument/ReSpeaker-4-Mic-Array-for-Raspberry-Pi/blob/master/ReSpeaker-4-Mic-Array-for-Raspberry-Pi.md
, and build alexa with "snowboy" wake-up word. I finished all the installation. When I say "snowboy", the LEDs on Respeaker are on but Alexa cannot talk back.

### What I Did

I input all the code on the link above and this is what I got if I say "snowboy" to Respeaker.

[INFO.docx](https://github.com/respeaker/avs/files/1757294/INFO.docx)

Thanks!!!

**Comment by xiongyihui** [comment]
Did you run `alexa-audio-check` which checks audio input and output?

Maybe check if `/etc/asound.conf` is the same with https://github.com/respeaker/seeed-voicecard/blob/master/asound_4mic.conf

**Comment by wangzt12** [comment]
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.front
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround21
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround21
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround40
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround41
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround50
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround51
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround71
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'defaults.bluealsa.device'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4996:(snd_config_expand) Args evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM bluealsa
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'defaults.bluealsa.device'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4996:(snd_config_expand) Args evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM bluealsa
ALSA lib pcm_dmix.c:990:(snd_pcm_dmix_open) The dmix plugin supports only playback stream
ALSA lib pcm_direct.c:1765:(snd1_pcm_direct_parse_open_conf) Unknown field ac108-slavepcm
ALSA lib pcm_direct.c:1765:(snd1_pcm_direct_parse_open_conf) Unknown field ac108-slavepcm
ALSA lib pcm_direct.c:1765:(snd1_pcm_direct_parse_open_conf) Unknown field ac108-slavepcm
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
RMS: 205
RMS: 187
RMS: 185
RMS: 221
RMS: 2611
This is what i got if I run alexa-audio-check.
/etc/asound.conf is the same. 
What should I do?

**Comment by xiongyihui** [comment]
The `alexa-audio-check` will play an alarm. If you didn't hear anything, the default audio output is not configured correctly or you forget to install the dependencies:

```
sudo apt-get install gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly \
gir1.2-gstreamer-1.0 python-gi python-gst-1.0 python-pyaudio
```

To check audio input and output, try:

```
arecord -f cd -v s.wav
aplay -v s.wav
```

**Comment by wangzt12** [comment]
Thanks! I install the dependencies. When I try arecord -f cd -v s.wav, I got this:
ALSA lib pcm_direct.c:1765:(snd1_pcm_direct_parse_open_conf) Unknown field ac108-slavepcm
arecord: main:788: audio open error: Invalid argument

**Comment by xiongyihui** [comment]
Oh, there is an error in the file `/etc/asound.conf`

You can re-install seeed-voicecard which updated https://github.com/respeaker/seeed-voicecard/blob/master/asound_4mic.conf

**Comment by wangzt12** [comment]
Thanks!!! Now arecord -f cd -v s.wav and aplay -v s.wav work fine! It can record and play the sound just recorded.
But alexa-audio-check still doesn't trigger any alarm. I got the same feedback as above if I run alexa-audio-check.

**Comment by xiongyihui** [comment]
That's weird! How about try to use other mp3 players?

```
sudo apt install gstreamer1.0-tools mpv vlc

gst-launch-1.0 playbin
 uri=https://archive.org/download/SuperMarioBros.ThemeMusic/SuperMarioBros.mp3

mpv https://archive.org/download/SuperMarioBros.ThemeMusic/SuperMarioBros.mp3

cvlc https://archive.org/download/SuperMarioBros.ThemeMusic/SuperMarioBros.mp3
```

**Comment by wangzt12** [comment]
The second and the third one work! How to set them as the player for Alexa??

**Comment by xiongyihui** [comment]
To change the player of Alexa, you need to modify https://github.com/respeaker/avs/blob/master/avs/player.py

But I think we need to figure out why gstreamer does't work. It's most likely that some gstreamer plugins are missing.

I just wonder which OS do you use? I got no problem with the latest raspbian. 

Make sure that all the dependencies are installed.
```
sudo apt-get install gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly
sudo apt-get install gir1.2-gstreamer-1.0 python-gi python-gst-1.0
```

**Comment by bennr01** [comment]
Hi,
i just had the same problem with the 2-mic array.
Running the following command as root fixed the problem for me:
`apt-get install gstreamer1.0-plugins-*`.
I hope this helps.

**Comment by wangzt12** [comment]
Doesn't work for me. I probably still need to change the player...

**Comment by wangzt12** [comment]
I reviewed the install process. When I install 
sudo apt install gstreamer1.0 gstreamer1.0-plugins-good gstreamer1.0-plugins-ugly
I got:

Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 gstreamer1.0-omx-dbg : Depends: gstreamer1.0-omx (= 1.0.0.1-0+rpi12+jessiepmg) but 1.10.4-1+rpt3 is to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by xiongyihui** [comment]
It is likely that the default of pi's gstreamer audio sink is GstOMXHdmiAudioSink. It ignores ALSA configurations (`/etc/asound.conf` or `~/.asoundrc`)

![image](https://user-images.githubusercontent.com/948283/37809628-105cfd74-2e8b-11e8-9863-19382cc8de30.png)

To verify if it's the case:

```
sudo apt-get install gstreamer1.0-tools
gst-launch-1.0 playbin uri=https://archive.org/download/SuperMarioBros.ThemeMusic/SuperMarioBros.mp3
# Audio output port should be HDMI

 gst-launch-1.0 playbin uri=https://archive.org/download/SuperMarioBros.ThemeMusic/SuperMarioBros.mp3  audio-sink=alsasink
# Audio output port should be the default alsa output device
```

If you don't want HDMI audio output, try:

```
sudo apt remove gstreamer1.0-omx gstreamer1.0-omx-rpi
```
