### ISSUE TITLE
AVS HTTP/2 implementation?

### ISSUE THREAD

**Issue by nouser2013** [respeaker/avs#20]
As the v1 API will be removed from Amazon Servers on April 30th, are you planning to update to http/2? And, consequently, the new endpoints given by Amazon here: https://developer.amazon.com/de/docs/alexa-voice-service/api-overview.html

Also, as interaction seems more complex in the new version regarding protocol/format, will you implement those changes as well?

**Comment by xiongyihui** [comment]
The library already uses the new API with http/2
