### ISSUE TITLE
Wake word issues

### ISSUE THREAD

**Issue by nouser2013** [respeaker/avs#21]
I do know about pocket sphinx, dictionary and the keyword file.

Installed with pip, and everything including ```alexa-tap``` is working. But, running ```alexa``` will not make the respeaker device start listening as a ENTER key press would with ```alexa-tap```.

- I'm not seeing relevant error messages (just "unhandled event"s).
- The red LED on the 6 mike array PCB lights up when I speak.
- I am seeing the ":on_ready" message.

What am I doing wrong?

Also, how would I change the wake word to something different, if I already put the appropriate entries into ```dictionary.txt``` and ```keywords.txt``` and the word is "jane" instead of "alexa"?

Thanks.

**Comment by xiongyihui** [comment]
Are you able to run [offline_voice_assistant.py](https://github.com/respeaker/respeaker_python_library/blob/master/examples/offline_voice_assistant.py)? Check if pocketsphinx does work or not

To change the keyword, after modifying dictionary.txt and keywords.txt, replace "alexa" with your keyword at https://github.com/respeaker/avs/blob/master/avs/main.py#L105

**Comment by nouser2013** [comment]
Hi, yes, it works now. Though, I must say that the PS engine is quite useless as configured here. It detects the Alexa keyword from me walking around, and, moreover, from AVS speechout. In any case, I changed the wake word, but had to introduce a flag which is set between https://github.com/respeaker/avs/blob/master/avs/main.py#L93 and L94 and cleared in on_finished.

https://github.com/respeaker/avs/blob/master/avs/main.py#L105 evaluates the flag and does nothing if device is currently speaking. I guess this can be closed.

**Comment by CorrederaJorge** [comment]
Hi:
I am having the same issue as you described here. I just got  ":on_ready" message. I am trying to run  offline_voice_assistant.py but the detection is not good. I  an accuracy more than 30%. Is it possible to do something like training the model again or so?.

How can I install for example Snowboy? How can I install libatlas-base-dev swig?

Kind regards.
