### ISSUE TITLE
Cannot hear output

### ISSUE THREAD

**Issue by meriki** [respeaker/avs#23]
* Python Alexa Voice Service version:
* Python version:
* Operating System:

### Description

Ran the repo as per README on Ubuntu. Where does the output go to? Cannot hear any output.

**Comment by meriki** [comment]
No, both the tests yield an output.  
I'm getting this error for get_response :
INFO:hyper.http20.connection:Received unhandled event <PriorityUpdated stream_id:5, weight:16, depends_on:0, exclusive:False>

**Comment by xiongyihui** [comment]
There are some updates. You can upgrade the latest avs library and try agian. To upgrade avs, run `pip install -U avs`

**Comment by meriki** [comment]
Hi! I realised that my microphone was malfunctioning. Thanks!
