### ISSUE TITLE
ERROR:root:need more than 2 values to unpack

### ISSUE THREAD

**Issue by Edwin-Luijten** [respeaker/avs#28]
* Python version: 2.7.13
* Operating System: Raspbian GNU/Linux 9.4

### Description

Tried to do python main.py

### What I Did

```
python main.py
```

This part of the code in alexa.py on line 153 is cousing the error:
```
try:
                event, listener, attachment = self.event_queue.get(
                    timeout=0.25)
            except queue.Empty:
                event = None
```

When i print the result of self.event_queue.get it shows below value:
```
{'header': {'namespace': 'System', 'name': 'SynchronizeState', 'messageId': '65d4301efd584e8ab2737e5986c803b0'}, 'payload': {}}
```

**Comment by xiongyihui** [comment]
Have you changed anything? Are you able to run `alexa-tap`?
