### ISSUE TITLE
when installing python audio over existing - it fails

### ISSUE THREAD

**Issue by alexeinz** [respeaker/avs#5]
root@ReSpeaker2:/usr/bin# pip install pyaudio respeaker --upgrade
Downloading/unpacking pyaudio from https://pypi.python.org/packages/ab/42/b4f04721c5c5bfc196ce156b3c768998ef8c0ae3654ed29ea5020c749a6b/PyAudio-0.2.11.tar.gz#md5=7e4c88139284033f67b4336c74eda3b8
  Downloading PyAudio-0.2.11.tar.gz
  Running setup.py (path:/tmp/pip_build_root/pyaudio/setup.py) egg_info for package pyaudio
    
Downloading/unpacking respeaker from https://pypi.python.org/packages/d1/9f/0ee68e8ab387f6a577e261359109b7943096c3c15bc34d0bd9f1900578fe/respeaker-0.5.0-py2.py3-none-any.whl#md5=b99c8716444e07221188aa1f96cbb826
  Downloading respeaker-0.5.0-py2.py3-none-any.whl (491kB): 491kB downloaded
Installing collected packages: pyaudio, respeaker
  Found existing installation: pyaudio 0.2.9
    Can't uninstall 'pyaudio'. No files were found to uninstall.
  Running setup.py install for pyaudio
    warning: build_py: byte-compiling is disabled, skipping.
    
    building '_portaudio' extension
    mipsel-openwrt-linux-uclibc-gcc -fno-strict-aliasing -Os -pipe -mno-branch-likely -mips32r2 -mtune=24kec -mdsp -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -DNDEBUG -fno-inline -DNDEBUG -Os -pipe -mno-branch-likely -mips32r2 -mtune=24kec -mdsp -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -fPIC -I/usr/include/python2.7 -c src/_portaudiomodule.c -o build/temp.linux-mips-2.7/src/_portaudiomodule.o
    unable to execute 'mipsel-openwrt-linux-uclibc-gcc': No such file or directory
    error: command 'mipsel-openwrt-linux-uclibc-gcc' failed with exit status 1
    Complete output from command /usr/bin/python2.7 -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/pyaudio/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-EtrAum-record/install-record.txt --single-version-externally-managed --compile:
    running install

running build

running build_py

creating build

creating build/lib.linux-mips-2.7

copying src/pyaudio.py -> build/lib.linux-mips-2.7

warning: build_py: byte-compiling is disabled, skipping.

running build_ext

building '_portaudio' extension

creating build/temp.linux-mips-2.7

creating build/temp.linux-mips-2.7/src

mipsel-openwrt-linux-uclibc-gcc -fno-strict-aliasing -Os -pipe -mno-branch-likely -mips32r2 -mtune=24kec -mdsp -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -DNDEBUG -fno-inline -DNDEBUG -Os -pipe -mno-branch-likely -mips32r2 -mtune=24kec -mdsp -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -fPIC -I/usr/include/python2.7 -c src/_portaudiomodule.c -o build/temp.linux-mips-2.7/src/_portaudiomodule.o

unable to execute 'mipsel-openwrt-linux-uclibc-gcc': No such file or directory

error: command 'mipsel-openwrt-linux-uclibc-gcc' failed with exit status 1

----------------------------------------
  Can't roll back pyaudio; was not uninstalled
Cleaning up...
Command /usr/bin/python2.7 -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/pyaudio/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-EtrAum-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/pyaudio
Storing debug log for failure in /root/.pip/pip.log

**Comment by xiongyihui** [comment]
pyaudio requires c compiler which is not available openwrt, so it need be cross-compiled. It'd better not upgrade the pyaudio.

**Comment by alexeinz** [comment]
but thats what your instructions are saying to run hands free alexa avs?
https://github.com/respeaker/respeaker_python_library

**Comment by alexeinz** [comment]
Can you then clarify how is it possible to run AVS hands free?

**Comment by xiongyihui** [comment]
pyaudio and respeaker python library are already installed on openwrt. no need to re-install them.
Just install avs, you will be about to run the hands-free `alexa`
```
pip install https://github.com/respeaker/avs/archive/master.zip
```

If `alexa` is still the old version after installing avs, run `python -m avs.main` to start the new alexa.

**Comment by alexeinz** [comment]
root@(none):/# alexa

INFO:mic:Start detecting

INFO:mic:Detected alexa

DEBUG:root:wakeup

INFO:mic:Start listening

INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection
(1): api.amazon.com

DEBUG:requests.packages.urllib3.connectionpool:"POST /auth/o2/token
HTTP/1.1" 400 94

WARNING:root:Failed to get token. HTTP status code 400

INFO:mic:Start detecting

INFO:mic:Stop listening

INFO:mic:Detected alexa

DEBUG:root:wakeup

INFO:mic:Start listening

------
Regards
Alex Einz

Tel - +81(0) 80-6749-1800
dj@alexeinz.info
http://www.alexeinz.info

Weekly quote:
“The true sign of intelligence is not knowledge but imagination
 - Albert Einstein
